apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  namespace: claims-demo
  labels:
    app: claims-processing
    component: backend
spec:
  to:
    kind: Service
    name: backend-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
