apiVersion: mcp.opendatahub.io/v1
kind: MCPServer
metadata:
  name: ocr-server
  namespace: claims-demo
  labels:
    app: claims-processing
    component: mcp-ocr
    mcp-role: ocr-processor
spec:
  # Server configuration
  displayName: "OCR Processing MCP Server"
  description: "MCP server for OCR processing with LLM validation"
  type: custom

  # Container image
  image: quay.io/claims-demo/ocr-server:latest
  imagePullPolicy: Always

  # Reference to LlamaStack for validation
  llamaStackRef: claims-llamastack

  # MCP Tools exposed by this server
  tools:
    - name: ocr_document
      description: "Extract text from document images using OCR and validate with LLM"
      inputSchema:
        type: object
        properties:
          document_path:
            type: string
            description: "Path to the document image or PDF file"
          document_type:
            type: string
            enum: ["claim_form", "invoice", "medical_record", "id_card", "other"]
            description: "Type of document being processed"
          language:
            type: string
            default: "eng"
            description: "OCR language code (eng, fra, spa, etc.)"
          enhance_image:
            type: boolean
            default: true
            description: "Apply image enhancement before OCR"
        required: ["document_path"]
      outputSchema:
        type: object
        properties:
          success:
            type: boolean
          raw_text:
            type: string
            description: "Raw OCR extracted text"
          structured_data:
            type: object
            description: "LLM-validated and structured data"
          confidence:
            type: number
            description: "OCR confidence score (0-1)"
          errors:
            type: array
            items:
              type: string

  # Environment variables for the MCP server
  env:
    - name: TESSERACT_CMD
      value: "/usr/bin/tesseract"
    - name: OCR_LANGUAGE
      value: "eng+fra"  # Support English and French
    - name: IMAGE_PREPROCESSING
      value: "true"
    - name: LLM_VALIDATION_ENABLED
      value: "true"
    - name: MAX_IMAGE_SIZE_MB
      value: "10"
    - name: LOG_LEVEL
      value: "INFO"

  # Resource requirements
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
      ephemeral-storage: 5Gi  # For temporary image processing
    limits:
      cpu: "2"
      memory: 4Gi
      ephemeral-storage: 10Gi

  # Volume mounts for document storage
  volumeMounts:
    - name: documents-storage
      mountPath: /mnt/documents
      readOnly: true

  volumes:
    - name: documents-storage
      persistentVolumeClaim:
        claimName: claims-documents-pvc

  # Health checks
  livenessProbe:
    httpGet:
      path: /health/live
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /health/ready
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  # Autoscaling configuration
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # Monitoring
  monitoring:
    enabled: true
    metrics:
      - ocr_documents_processed_total
      - ocr_processing_duration_seconds
      - ocr_confidence_score
      - ocr_errors_total

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    capabilities:
      drop:
        - ALL
