apiVersion: mcp.opendatahub.io/v1
kind: MCPServer
metadata:
  name: rag-server
  namespace: claims-demo
  labels:
    app: claims-processing
    component: mcp-rag
    mcp-role: retrieval-augmented-generation
spec:
  # Server configuration
  displayName: "RAG Retrieval MCP Server"
  description: "MCP server for vector search and retrieval-augmented generation"
  type: custom

  # Container image
  image: quay.io/claims-demo/rag-server:latest
  imagePullPolicy: Always

  # Reference to LlamaStack for embeddings and synthesis
  llamaStackRef: claims-llamastack

  # MCP Tools exposed by this server
  tools:
    - name: retrieve_user_info
      description: "Retrieve user information and contracts using vector search"
      inputSchema:
        type: object
        properties:
          user_id:
            type: string
            description: "Unique user identifier"
          query:
            type: string
            description: "Natural language query about user information"
          top_k:
            type: integer
            default: 5
            description: "Number of top results to return"
          include_contracts:
            type: boolean
            default: true
            description: "Include user contracts in search"
        required: ["user_id", "query"]
      outputSchema:
        type: object
        properties:
          user_info:
            type: object
            description: "Retrieved and synthesized user information"
          contracts:
            type: array
            description: "Relevant user contracts"
            items:
              type: object
          similarity_scores:
            type: array
            items:
              type: number
          source_documents:
            type: array
            description: "Original source documents used"

    - name: retrieve_similar_claims
      description: "Find similar historical claims using vector similarity search"
      inputSchema:
        type: object
        properties:
          claim_text:
            type: string
            description: "Text description of the current claim"
          claim_type:
            type: string
            description: "Type of claim (optional filter)"
          top_k:
            type: integer
            default: 10
            description: "Number of similar claims to return"
          min_similarity:
            type: number
            default: 0.7
            description: "Minimum similarity threshold (0-1)"
        required: ["claim_text"]
      outputSchema:
        type: object
        properties:
          similar_claims:
            type: array
            items:
              type: object
              properties:
                claim_id:
                  type: string
                claim_text:
                  type: string
                similarity_score:
                  type: number
                outcome:
                  type: string
                processing_time:
                  type: number

    - name: search_knowledge_base
      description: "Search the knowledge base for relevant policy information"
      inputSchema:
        type: object
        properties:
          query:
            type: string
            description: "Search query"
          filters:
            type: object
            description: "Optional filters (policy_type, date_range, etc.)"
          top_k:
            type: integer
            default: 5
        required: ["query"]
      outputSchema:
        type: object
        properties:
          results:
            type: array
            description: "Retrieved knowledge base articles"
          synthesized_answer:
            type: string
            description: "LLM-synthesized answer from retrieved context"

  # Environment variables
  env:
    - name: POSTGRES_HOST
      value: "postgresql-service.claims-demo.svc.cluster.local"
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_DB
      value: "claims_db"
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgresql-secret
          key: username
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql-secret
          key: password
    - name: VECTOR_DIMENSION
      value: "768"  # Must match embedding model dimension
    - name: SIMILARITY_METRIC
      value: "cosine"  # cosine, l2, inner_product
    - name: EMBEDDING_MODEL
      value: "sentence-transformers/all-mpnet-base-v2"
    - name: CACHE_ENABLED
      value: "true"
    - name: CACHE_TTL_SECONDS
      value: "3600"
    - name: LOG_LEVEL
      value: "INFO"

  # Resource requirements
  resources:
    requests:
      cpu: "500m"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

  # Health checks
  livenessProbe:
    httpGet:
      path: /health/live
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readinessProbe:
    httpGet:
      path: /health/ready
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  # Autoscaling configuration
  autoscaling:
    enabled: true
    minReplicas: 2  # Keep 2 replicas for high availability
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 75

  # Monitoring
  monitoring:
    enabled: true
    metrics:
      - rag_queries_total
      - rag_query_duration_seconds
      - rag_similarity_scores
      - rag_cache_hits_total
      - rag_cache_misses_total
      - rag_vector_db_errors_total

  # Connection pooling for PostgreSQL
  connectionPool:
    minSize: 5
    maxSize: 20
    maxIdleTime: 300

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    capabilities:
      drop:
        - ALL
